In [1]:
import numpy as np

In [3]:
# Create a 1D NumPy array
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [8]:
# Create a 4×5 array of zeros. Then create another 4×5 array of ones. Add them together.
arr1 = np.zeros((4,5))
arr2 = np.ones((4,5))
add = arr1 + arr2
print(add)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
# Create an array of 8 evenly spaced values between 0 and 1 using linspace()
arr1 = np.linspace(0,1,8)
arr1

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        ])

In [13]:
# Create np.arange(1,25) and reshape into a 4×6 matrix. Print shape, dimensions and dtype.
arr1=np.arange(1,25)
arr2=arr1
print(arr2)
arr3 = arr2.reshape(4,6)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [14]:
arr3.shape

(4, 6)

In [16]:
arr.ndim

2

In [17]:
arr.dtype

dtype('float64')

In [18]:
arr = [10, 20, 30, 40, 50, 60, 70, 80, 90,100]
print(arr[0:5])

[10, 20, 30, 40, 50]


In [31]:
print(arr[7:11])
print(arr[-3:])

[80, 90, 100]
[80, 90, 100]


In [33]:
print(arr[0::2])
print(arr[::2])

[10, 30, 50, 70, 90]
[10, 30, 50, 70, 90]


In [35]:
# Create a 5×5 array using np.arange(25).reshape(5,5)
arr=np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
print(arr[2])

[10 11 12 13 14]


In [39]:
print(arr[:,3])

[ 3  8 13 18 23]


In [41]:
print(arr[:3, 2:])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [42]:
# Create array = [1,2,3,4,5]
# Add 100 to every element
# Multiply every element by 3
# Without any loop
arr = np.array([1,2,3,4,5])
print(arr + 100)

[101 102 103 104 105]


In [43]:
print(arr * 3)

[ 3  6  9 12 15]


In [44]:
#  Broadcasting
# Create two arrays:
a = np.array([1,2,3])
b = np.array([1,2,3])

print("a+b =", a+b)
print("a-b =", a-b)
print("a*b =", a*b)
print("a/b =", a/b)

a+b = [2 4 6]
a-b = [0 0 0]
a*b = [1 4 9]
a/b = [1. 1. 1.]


In [45]:
# Given scores = [72, 85, 91, 68, 74, 88, 62, 95, 77,
# 80], compute: mean, median (np.median), std,
# min, max, and range (max-min).

In [46]:
arr = np.array([72,85,91,68,74,88,92,95,77,81])

In [47]:
print(np.mean(arr))

82.3


In [48]:
print(np.median(arr))

83.0


In [49]:
print(np.std(arr))

8.832326986700616


In [50]:
print(np.min(arr))

68


In [51]:
print(np.max(arr))

95


In [52]:
print(np.max(arr)-np.min(arr))

27


In [53]:
# For a 3×4 random integer array
# (np.random.randint(1,100,size=(3,4))): compute
# sum across all elements, row-wise sum (axis=1),
# and column-wise mean (axis=0).

In [54]:
arr = np.random.randint(1,100,size=(3,4))
print(arr)

[[68 49 68 63]
 [61 17 45 71]
 [40 57 17 78]]


In [56]:
# Row-wise Sum (axis=1)
print(np.sum(arr, axis=1))

[248 194 192]


In [57]:
# Column-wise Mean (axis=0)
print(np.mean(arr, axis=0))

[56.33333333 41.         43.33333333 70.66666667]
